@startuml Animal Monitoring System - Class Diagram
skinparam dpi 150

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml

title Система мониторинга животных - Диаграмма классов

top to bottom direction

' user
package "user" {
    class UserRoleEnum <<enumeration>> {
        +String role1
        +String role2
        +String role3
        +String role4
    }

    class UserModel {
        +String name
        +String email
        +UserRoleEnum user_role
    }

    class UserRepository {
        +list_users(): List<User>
        +get_user(): User
        +create_user(): User
        +update_user(): User
        +delete_user(): void
    }

    class Dictionary {
        +String refresh
        +String access
    }

    class LoginResponse {
        +Dictionary token_data
        +User user_data
    }

    class UserServices {
        +list_users(): List<User>
        +get_user(): User
        +create_user(): User
        +update_user(): User
        +delete_user(): void
    }

    class AuthServices {
        +_check_user_password_is_valid(): boolean
        +_hash_user_password(): bytes
        +_generate_access_and_refresh_token(): Dictionary
    }

    class UserController {
        +list_users(): List<User>
        +get_user(): User
        +create_user(): User
        +update_user(): User
        +delete_user(): void
    }
    class AuthController {
        +LoginResponse login()
        +String issue_access_token()
    }

    UserModel "1" -- "1" UserRoleEnum : includes >
    AuthServices "1" -- "1" Dictionary : includes >
    UserRepository ..> UserModel : uses >
    UserServices ..> UserRepository : uses >
    AuthController ..> UserServices : uses >
    AuthController ..> AuthServices : uses >

    UserController ..> UserServices : uses >
    UserController ..> AuthServices : uses >
    AuthController "1" -- "0..*" LoginResponse : manages >
}


' analytics
package "analytics" {
    class ResponseType <<enumeration>> {
        +string success
        +string failed
    }

    class Error {
        +int error_code
        +string error_text
    }

    class Response {
        +int response_id
        +ResponseType response
        +error: Error?
    }

    class Metrics {}
    class MetricsRepository {
        +get_metrics(): Metrics
        +add_metrics(): void
        +delete_metrics(): void
    }
    class MetricsServices {
        +get_metrics(): Metrics
        +add_metrics(): void
        +delete_metrics(): void
    }
    class MetricsController {
        +get_metrics(): Metrics
        +add_metrics(): Response
        +delete_metrics(): Response
    }

    class MonitoringData {}
    class MonitoringDataController {
        +get_monitoring_data(metrics): MonitoringData
    }

    class Analytics {}


    class AnalyticsServices {
        +save_analytics(): void
        +clean_analytics(): void
    }

    class FunctionType {
        +execute(): void
    }
    class AnalyticsServices {
        -FunctionType _celery_task()
        +generate_analytics(): Analytics
        +save_analytics(): void
        +clean_analytics(): void
        -_call_celery_task(): void
    }
    class AnalyticsController {
        +request_analytics(): ResponseType
        +get_analytics(): ResponseType | Analytics
    }

    Response "1" -- "1" ResponseType : includes >
    Response "1" -- "1" Error : includes >
    AnalyticsServices "1" -- "1" FunctionType: includes >

    MetricsRepository "1" -- "0..*" Metrics : manages >
    MetricsServices ..> MetricsRepository : uses >
    MetricsController ..> MetricsServices : uses >

    AnalyticsServices ..> AnalyticsRepository : uses >
    AnalyticsServices ..> MetricsRepository : uses >
    AnalyticsServices ..> MonitoringDataController : uses >
    AnalyticsController ..> AnalyticsServices : uses >

    AnalyticsController "1" -- "0..*" Response : manages >
    AnalyticsServices "1" -- "0..*" Analytics : manages >
    MonitoringDataController "1" -- "0..*" MonitoringData : manages >
    MonitoringDataController "1" -- "0..*" Response : manages >
}


' central_server_application
package "central_server_application" {
    class Authorisation {
        login_controller(): UserModel
        registration_controller(): UserModel
    }

    class AuthMiddleware {
        verify_jwt_access_token(): Response
    }


    class MetricsControllers {
        get_metrics_controller(): Metrics
        add_metrics_controller(): void
        delete_metrics_controller():void
        get_metrics_data_controller(): Analytics
    }

    class ExternalSystemsController {
        get_metrics_controller(): Metrics
    }
    class MetricsServices {
        get_metrics_controller(): Metrics
        add_metrics_controller(): void
        delete_metrics_controller():void
        get_metrics_data_controller(): Analytics
    }


    class EventTypeEnum <<enumeration>> {
        +string warn
        +string notivication
        +string event
    }
    class ProducerTypeEnum <<enumeration>> {
        +string resources_monitoring
        +string equipment_control
        +string animals_behaviour_monitoring
    }

    class Event {
        +string time
        +EventTypeEnum event_type
        +ProducerTypeEnum producer_type
    }
    class ResourcesControlConsumer {
        consume(): Event
    }
    class EquipmentControlConsumer {
        consume(): Event
    }
    class AnimalsBehaviourMonitoringConsumer {
        consume(): Event
    }

    class ResourcesMonitoringServices {
        notify_ws():void
    }
    class EquipmentControlServices {
        notify_ws():void
    }
    class AnimalsBehaviourMonitoringServices {
        notify_ws():void
    }

    class WebsocketsUiConnector {
        notify_ui(): void
        notify_mobile_app(): void
    }

    class Command{}
    class EquipmentControlConnectorMainServer {
        send_command(command: Command): Response
    }
    class EquipmentControlController {
        send_command(command: Command): Response
    }

    Event "1" -- "1" EventTypeEnum: includes >
    Event "1" -- "1" ProducerTypeEnum: includes >

    ResourcesControlConsumer ..> ResourcesMonitoringServices : uses >
    ResourcesControlConsumer "1" -- "0..*" Event : manages >

    EquipmentControlConsumer ..> EquipmentControlServices : uses >
    EquipmentControlConsumer "1" -- "0..*" Event : manages >
    EquipmentControlConnectorMainServer "1" -- "0..*" Command : manages >

    AnimalsBehaviourMonitoringConsumer ..> AnimalsBehaviourMonitoringServices : uses >
    AnimalsBehaviourMonitoringConsumer "1" -- "0..*" Event : manages >

    ResourcesMonitoringServices ..> WebsocketsUiConnector : uses >
    EquipmentControlServices ..> WebsocketsUiConnector : uses >
    AnimalsBehaviourMonitoringServices ..> WebsocketsUiConnector : uses >

    AuthMiddleware ..> MetricsControllers : uses >
    AuthMiddleware ..> ExternalSystemsController : uses >
    MetricsControllers ..> MetricsServices : uses >
    ExternalSystemsController ..> MetricsServices : uses >

    AuthMiddleware ..> EquipmentControlController : uses >
    EquipmentControlController ..> EquipmentControlConnectorMainServer : uses >
    AuthMiddleware -- WebsocketsUiConnector : related
}

package "resources_monitoring_server" {
    class FoorageMonitoringData {}
    class FoorageMonitoringController {
        -FoorageMonitoringServices _services
        -ResourcesMonitoringPublisher _publisher

        +recieve_monitoring_data(): void
        -_save_monitoring_data(): void
        -_warn_operator(): Event
        +provide_monitoring_data(): Event
        +delete_monitoring_data(): void
    }
    class FoorageMonitoringServices {
        -FoorageMonitoringRepository _repository

        +analyze_incoming_data_and_notify_operator(): boolean
        +save_monitoring_data(): void
        +get_monitoring_data(): Event
        +delete_monitoring_data(): void
    }
    class FoorageMonitoringRepository {
        +save_monitoring_data(): void
        +get_monitoring_data(): Event
        +delete_monitoring_data(): void
    }

    class WaterFiltersMonitoringData {}
    class WaterFiltersController {
        -WaterFiltersServices _services
        -ResourcesMonitoringPublisher _publisher

        recieve_monitoring_data():void
        -_save_monitoring_data(): void
        -_warn_operator(): Event
        +provide_monitoring_data(): Event
        +delete_monitoring_data(): void
    }
    class WaterFiltersServices {
        +WaterFiltersRepository _repository
        +analyze_incoming_data_and_notify_operator(): boolean
        +save_monitoring_data(): void
        +get_monitoring_data(): Event
        +delete_monitoring_data(): void
    }
    class WaterFiltersRepository {
        +save_monitoring_data(): void
        +get_monitoring_data(): Event
        +delete_monitoring_data(): void
    }

    class ResourcesMonitoringPublisher {
        +publish_event(): Event
    }

    FoorageMonitoringRepository "1" -- "0..*" FoorageMonitoringData : manages >
    FoorageMonitoringServices ..> FoorageMonitoringRepository : uses >
    FoorageMonitoringController ..> FoorageMonitoringServices : uses >
    FoorageMonitoringController ..> ResourcesMonitoringPublisher : uses >

    WaterFiltersRepository "1" -- "0..*" WaterFiltersMonitoringData : manages >
    WaterFiltersServices ..> WaterFiltersRepository : uses >
    WaterFiltersController ..> WaterFiltersServices : uses >
    WaterFiltersController ..> ResourcesMonitoringPublisher : uses >
}

package "equipment_control_server" {
    class FeedersControlMonitoringData {}
    class FeedersControlMonitoringController {
        -FeedersControlMonitoringServices _services
        -EquipmentControlPublisher _publisher

        +recieve_monitoring_data(): void
        +recieve_central_server_command(command:Command): Response
        -_send_command_to_equipment(command:Command): Response
        -_save_monitoring_data(): void
        -_warn_operator(): Event
        +provide_monitoring_data(): Event
        +delete_monitoring_data(): void
    }
    class FeedersControlMonitoringServices {
        -FeedersControlMonitoringRepository _repository

        +analyze_incoming_data_and_notify_operator(): boolean
        +save_monitoring_data(): void
        +get_monitoring_data(): Event
        +delete_monitoring_data(): void
    }
    class FeedersControlMonitoringRepository {
        +save_monitoring_data(): void
        +get_monitoring_data(): Event
        +delete_monitoring_data(): void
    }

    class WaterBowlsControlMonitoringData {}
    class WaterBowlsControlController {
        -WaterBowlsControlServices _services
        -EquipmentControlPublisher _publisher

        recieve_monitoring_data():void
        +recieve_central_server_command(command:Command): Response
        -_send_command_to_equipment(command:Command): Response
        -_save_monitoring_data(): void
        -_warn_operator(): Event
        +provide_monitoring_data(): Event
        +delete_monitoring_data(): void
    }
    class WaterBowlsControlServices {
        +WaterBowlsControlRepository _repository
        +analyze_incoming_data_and_notify_operator(): boolean
        +save_monitoring_data(): void
        +get_monitoring_data(): Event
        +delete_monitoring_data(): void
    }
    class WaterBowlsControlRepository {
        +save_monitoring_data(): void
        +get_monitoring_data(): Event
        +delete_monitoring_data(): void
    }

    class EquipmentControlPublisher {
        +publish_event(): Event
    }

    FeedersControlMonitoringRepository "1" -- "0..*" FeedersControlMonitoringData : manages >
    FeedersControlMonitoringServices ..> FeedersControlMonitoringRepository : uses >
    FeedersControlMonitoringController ..> FeedersControlMonitoringServices : uses >
    FeedersControlMonitoringController ..> EquipmentControlPublisher : uses >

    WaterBowlsControlRepository "1" -- "0..*" WaterBowlsControlMonitoringData : manages >
    WaterBowlsControlServices ..> WaterBowlsControlRepository : uses >
    WaterBowlsControlController ..> WaterBowlsControlServices : uses >
    WaterBowlsControlController ..> EquipmentControlPublisher : uses >
}



package "animals_behaviour_monitoring" {
    class AnimalsDeviantBehaviourControlMonitoringData {}
    class AnimalsDeviantBehaviourControlController {
        -AnimalsDeviantBehaviourControlServices _services
        -AnimalsBehaviourMonitoringPublisher _publisher

        +recieve_monitoring_data(): void
        -_save_monitoring_data(): void
        -_warn_operator(): Event
        +provide_monitoring_data(): Event
        +delete_monitoring_data(): void
    }
    class AnimalsDeviantBehaviourControlServices {
        -AnimalsDeviantBehaviourControlRepository _repository

        +analyze_incoming_data_and_notify_operator(): boolean
        +save_monitoring_data(): void
        +get_monitoring_data(): Event
        +delete_monitoring_data(): void
    }
    class AnimalsDeviantBehaviourControlRepository {
        +save_monitoring_data(): void
        +get_monitoring_data(): Event
        +delete_monitoring_data(): void
    }

    class SignsOfPigletsBeingCrushedDetectionMonitoringData {}
    class SignsOfPigletsBeingCrushedDetectionController {
        -SignsOfPigletsBeingCrushedDetectionServices _services
        -AnimalsBehaviourMonitoringPublisher _publisher

        recieve_monitoring_data():void
        -_save_monitoring_data(): void
        -_warn_operator(): Event
        +provide_monitoring_data(): Event
        +delete_monitoring_data(): void
    }
    class SignsOfPigletsBeingCrushedDetectionServices {
        +SignsOfPigletsBeingCrushedDetectionRepository _repository
        +analyze_incoming_data_and_notify_operator(): boolean
        +save_monitoring_data(): void
        +get_monitoring_data(): Event
        +delete_monitoring_data(): void
    }
    class SignsOfPigletsBeingCrushedDetectionRepository {
        +save_monitoring_data(): void
        +get_monitoring_data(): Event
        +delete_monitoring_data(): void
    }



    class AnimalExteriorAuditMonitoringData {}
    class AnimalExteriorAuditController {
        -AnimalExteriorAuditServices _services
        -AnimalsBehaviourMonitoringPublisher _publisher

        recieve_monitoring_data():void
        -_save_monitoring_data(): void
        -_warn_operator(): Event
        +provide_monitoring_data(): Event
        +delete_monitoring_data(): void
    }
    class AnimalExteriorAuditServices {
        +AnimalExteriorAuditRepository _repository
        +analyze_incoming_data_and_notify_operator(): boolean
        +save_monitoring_data(): void
        +get_monitoring_data(): Event
        +delete_monitoring_data(): void
    }
    class AnimalExteriorAuditRepository {
        +save_monitoring_data(): void
        +get_monitoring_data(): Event
        +delete_monitoring_data(): void
    }


    class CountAnimalsSystemMonitoringData {}
    class CountAnimalsSystemController {
        -CountAnimalsSystemServices _services
        -AnimalsBehaviourMonitoringPublisher _publisher

        recieve_monitoring_data():void
        -_save_monitoring_data(): void
        -_warn_operator(): Event
        +provide_monitoring_data(): Event
        +delete_monitoring_data(): void
    }
    class CountAnimalsSystemServices {
        +CountAnimalsSystemRepository _repository
        +analyze_incoming_data_and_notify_operator(): boolean
        +save_monitoring_data(): void
        +get_monitoring_data(): Event
        +delete_monitoring_data(): void
    }
    class CountAnimalsSystemRepository {
        +save_monitoring_data(): void
        +get_monitoring_data(): Event
        +delete_monitoring_data(): void
    }

    class AnimalsBehaviourMonitoringPublisher {
        +publish_event(): Event
    }

    AnimalsDeviantBehaviourControlRepository "1" -- "0..*" AnimalsDeviantBehaviourControlMonitoringData : manages >
    AnimalsDeviantBehaviourControlServices ..> AnimalsDeviantBehaviourControlRepository : uses >
    AnimalsDeviantBehaviourControlController ..> AnimalsDeviantBehaviourControlServices : uses >
    AnimalsDeviantBehaviourControlController ..> AnimalsBehaviourMonitoringPublisher : uses >

    SignsOfPigletsBeingCrushedDetectionRepository "1" -- "0..*" SignsOfPigletsBeingCrushedDetectionMonitoringData : manages >
    SignsOfPigletsBeingCrushedDetectionServices ..> SignsOfPigletsBeingCrushedDetectionRepository : uses >
    SignsOfPigletsBeingCrushedDetectionController ..> SignsOfPigletsBeingCrushedDetectionServices : uses >
    SignsOfPigletsBeingCrushedDetectionController ..> AnimalsBehaviourMonitoringPublisher : uses >

    AnimalExteriorAuditRepository "1" -- "0..*" AnimalExteriorAuditMonitoringData : manages >
    AnimalExteriorAuditServices ..> AnimalExteriorAuditRepository : uses >
    AnimalExteriorAuditController ..> AnimalExteriorAuditServices : uses >
    AnimalExteriorAuditController ..> AnimalsBehaviourMonitoringPublisher : uses >

    CountAnimalsSystemRepository "1" -- "0..*" CountAnimalsSystemMonitoringData : manages >
    CountAnimalsSystemServices ..> CountAnimalsSystemRepository : uses >
    CountAnimalsSystemController ..> CountAnimalsSystemServices : uses >
    CountAnimalsSystemController ..> AnimalsBehaviourMonitoringPublisher : uses >
}
@enduml