@startuml Animal Monitoring System - Context Diagram

skinparam dpi 150
skinparam maxWidth 100000
skinparam maxHeight 50000

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

title Система мониторинга животных - Диаграмма Контекста

left to right direction

Person(operator, "Оператор")


System(equipment_control, "Система управления оборудованием", "Контролирует поилки и кормушки")
System(animals_behaviour_monitoring, "Система мониторинга поведения животных", "Осуществляет контроль состояния и поведения животных, выполняет подсчёт")
System(resources_monitoring, "Система мониторинга реурсов", "Осуществляет контроль запасов фуража и состояния водяных фильтров")
System(external_systems, "Внешние системы")
System(kafka, "Брокер сообщений", "Apache Kafka")

System(user_interface, "Пользовательский интерфейс", "React")
System(mobile_app, "Мобильное приложение", "React native")

System_Boundary(central_server, "Центральный сервер") {
        System(user, "Данные пользователя", "Python/SQLALchemy")
        System(analytics, "Аналитическая система", "Получает и анализирует метрики от систем мониторинга")
        System(central_server_main_app, "Центральный сервер")
        
        central_server_main_app <--> analytics : "Данные аналитики"
        central_server_main_app <--> user : "Данные пользователей"
}

resources_monitoring --> kafka : "Оповещения о внештатных ситуациях", "Kafka"
equipment_control --> kafka :"Оповещения о внештатных ситуациях", "Kafka"
animals_behaviour_monitoring --> kafka : "Оповещения о внештатных ситуациях", "Kafka protocol"
kafka --> central_server_main_app : "Оповещения о внештатных ситуациях", "Kafka protocol"

equipment_control <--> central_server_main_app :"Поток команд/Подтверждение выполнения", "gRPC"
resources_monitoring <--> central_server_main_app :"Запросы данных/данные систем мониторинга", "gRPC"
animals_behaviour_monitoring <--> central_server_main_app :"Запросы данных/данные систем мониторинга", "gRPC"

kafka --> central_server_main_app :"Оповещения о внештатных ситуациях"

central_server_main_app <--> user_interface :"Cериализованные данные", "JSON"
central_server_main_app <--> mobile_app :"Cериализованные данные", "JSON"

user_interface --> operator :"Данные системы"
mobile_app --> operator :"Данные системы"

central_server_main_app --> external_systems :"Предоставляет данные аналитической системы"
@enduml
